[pip] Fix import syntax to enable shutil.which check
In PR 1585 a syntax error was introduced  as `shutil.which` is a method of the Python
'shutil' module and not a module, so the proper import is `from shutil import which`
as regradless of the CPython version `import shutil.which` will result in a

ModuleNotFoundError: No module named 'shutil.which'; 'shutil' is not a package

This error was causing all runs of packaging/wheel/install.sh to use the legacy behavior
of `python setup.py install` regardless if `shutil.which` was available or not.